honor-http-proxy

keyserver hkps://keys.openpgp.org
keyserver hkps://keyserver.ubuntu.com

# Privacy-conscious defaults
standard-resolver

# Avoid legacy pools
disable-ipv6

hkp-cacert /etc/ssl/cert.pem

max-replies 5
