add_newline = false

format = "$directory$git_branch$git_status$character"

[directory]
truncation_length = 3
style = "bold #B48EAD"

[git_branch]
symbol = " "
style = "bold #EBCB8B"
format = "[$symbol$branch ]($style)"

[git_status]
style = "#81A1C1"
format = "([$all_status$ahead_behind ]($style))"

[character]
success_symbol = "[❯](#A3BE8C)"
error_symbol = "[❯](#BF616A)"
vicmd_symbol = "[❮](#81A1C1)"
